name: Build and push image to ECR
on: push
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAW4XSR34UOZBQPI6S
        aws-secret-access-key: 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
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: building image
      run: docker build -t gitactions .
    - name: taging image
      run: docker tag gitactions:latest 474028826408.dkr.ecr.us-east-1.amazonaws.com/gitactions:latest
    - name: pushing image
      run: docker push 474028826408.dkr.ecr.us-east-1.amazonaws.com/gitactions:latest
