name: Build and push image to ECR
on: push
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAW4XSR34UIOSRIVPI
        aws-secret-access-key: 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
        aws-region: ap-south-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: building image
      run: docker build -t github-sample .
    - name: taging image
      run: docker tag github-sample:latest 474028826408.dkr.ecr.ap-south-1.amazonaws.com/github-sample:latest
    - name: pushing image
      run: docker push 474028826408.dkr.ecr.ap-south-1.amazonaws.com/github-sample:latest
    - name: install-aws-cli
      uses: unfor19/install-aws-cli-action@master
    - run: aws --version
      shell: bash
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with: 
        version: v1.3.7 
    - name: Terraform Init
      id: init
      run: terraform init
      
    - name: Terraform Plan
      id: plan
      run: terraform plan
      
    - name: Terraform apply
      id: apply
      run: terraform apply --auto-approve 
    - name: Deploy Docker Image to EC2
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.PUBLIC_SSH_KEY }}
       username: ec2-user
       key: ${{ secrets.PRIVATE_SSH_KEY }}
       run:
         sudo docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
         sudo docker run $IMAGE_TAG
